### ISSUE TITLE
Checklist: Proof of Concept (Auto Scaling Notifications w/SNS & Lambda)

### ISSUE THREAD

**Issue by tonyhburns** [tonyhburns/vault-ec2-autoscaling#3]
This is the implementation checklist for creating a full proof of concept for the system described in #1.

- [ ] Rails App: A very simple Rails application that can upload files to S3. Uses App ID authentication with Vault to retrieve rotating AWS credentials to an IAM role that allows upload to an S3 bucket, and rotating DB credentials to the Database Server (figuring out how to properly allow for rotation of the DB credentials within the Rails application is a tangential but also interesting proof of concept)
- [ ] Bastion/NAT AMI: Packer template for a combined NAT host and bastion host that allows access to the private subnet where the app servers live
- [ ] App Server AMI: Packer template to create the AMI for running the Rails app
- [ ] Vault/Consul AMI: Packer template to create the AMI for running Vault and Consul
- [ ] Database Server: An RDS server with the database for the Rails application
- [ ] Elastic load balancer: Load balances requests to the app server auto scaling groups
- [ ] Terraform template to create a new VPC with all of the necessary networking components, security groups, bootstrap a Vault and Consul cluster, a Deployment Repository, and an auto scaling groups that run the app servers
- [ ] Scripts to create/delete a new cluster via the Terraform template
- [ ] RSpec/ServerSpec suite to verify that the system works by creating new auto scaling groups and running black box tests against the web service (e.g. upload a file successfully via the service)
